server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/qms
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: luolin123

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.rk.app.bean
logging:
  level:
    com:
      rk: trace




