server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://114.55.238.138:3306/qms
    driver-class-name: com.mysql.jdbc.Driver
    username: qms
    password: 123456

mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.rk.app.bean
logging:
  level:
    com:
      rk: trace




